# Generated by Django 5.0.3 on 2024-03-16 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=200, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, null=True, verbose_name='Apellidos')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, max_length=200, null=True, verbose_name='Género')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('organizacion', models.CharField(max_length=200, null=True, verbose_name='Organizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gincana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre de la gincana')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descirpción de la gincana')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('edicion', models.IntegerField(blank=True, null=True, verbose_name='Edición de la gincana')),
                ('visibilidad', models.BooleanField(default=False, verbose_name='Visibilidad de la gincana')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='gincana/', verbose_name='Imagen de la gincana')),
                ('email_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
