# Generated by Django 4.2.11 on 2024-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='nombre',
            field=models.CharField(default='default', max_length=100, verbose_name='Nombre de la parada'),
        ),
    ]
