# Generated by Django 5.0.3 on 2024-03-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='profesor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País'),
        ),
    ]
