# Generated by Django 5.0.3 on 2024-03-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_profesor_telefono_profesor_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gincana',
            name='edicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edición de la gincana'),
        ),
        migrations.CreateModel(
            name='GincanaJugada',
            fields=[
                ('duración', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Duración')),
                ('total_puntos', models.IntegerField(blank=True, null=True, verbose_name='Puntuación')),
                ('edición', models.DateTimeField(auto_now_add=True, verbose_name='Edición')),
                ('gincana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.gincana')),
            ],
        ),
    ]
