# Generated by Django 4.2.11 on 2024-06-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_parada_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacion',
            name='puntuacion',
        ),
    ]
