# Generated by Django 5.0.3 on 2024-03-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_gincana_imagen_alter_gincana_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='username',
        ),
    ]
