# Generated by Django 4.2.11 on 2024-04-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_verificacion_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('gincana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.gincana')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.parada')),
            ],
        ),
        migrations.AlterField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to='', verbose_name='Imagen de Perfil'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=254)),
                ('puntos', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.pregunta')),
            ],
        ),
    ]
