# Generated by Django 4.2.11 on 2024-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_parada_pregunta_alter_profesor_imagen_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
