# Generated by Django 5.0.3 on 2024-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_gincana_edicion_gincanajugada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gincana',
            name='activa',
            field=models.BooleanField(default=False, verbose_name='Visibilidad de la gincana'),
        ),
    ]
