# Generated by Django 4.2.11 on 2024-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_puntuacion_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='id',
            field=models.IntegerField(default=0, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='gincana',
            name='visibilidad',
            field=models.BooleanField(default=False, verbose_name='Gincana Pública: '),
        ),
    ]
