# Generated by Django 5.0.3 on 2024-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_profesor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
