# Generated by Django 5.0.3 on 2024-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_profesor_apellidos_alter_profesor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='genero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='organizacion',
            field=models.CharField(max_length=200, null=True, verbose_name='Organizacion'),
        ),
    ]
