# Generated by Django 5.0.3 on 2024-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_gincana_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gincanajugada',
            name='duración',
        ),
        migrations.AddField(
            model_name='gincana',
            name='duracion',
            field=models.TimeField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='gincanajugada',
            name='duracion',
            field=models.TimeField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='gincanajugada',
            name='edición',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Edición'),
        ),
    ]
