# Generated by Django 4.2.11 on 2024-04-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_parada_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
