# Generated by Django 5.0.3 on 2024-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_profesor_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
