# Generated by Django 4.2.11 on 2024-04-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_respuesta_es_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='num_respuestas',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=2),
        ),
    ]
