# Generated by Django 5.0.3 on 2024-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_gincanajugada_duración_gincana_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gincana',
            name='activa',
            field=models.BooleanField(default=False, verbose_name='Actividad de la gincana'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='genero',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True, verbose_name='Género'),
        ),
    ]
