# Generated by Django 4.2.11 on 2024-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_pregunta_num_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gincana',
            name='imagen',
            field=models.ImageField(blank=True, default='mapa.png', null=True, upload_to='', verbose_name='Imagen de la gincana'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='latitud',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='longitud',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.TextField(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='num_respuestas',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=2, verbose_name='Numero de Respuestas'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='es_correcta',
            field=models.BooleanField(default=False, verbose_name='Es Correcta/Fallo'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='puntos',
            field=models.IntegerField(verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(max_length=254, verbose_name='Respuesta'),
        ),
    ]
