# Generated by Django 5.0.3 on 2024-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_profesor_genero_alter_profesor_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País'),
        ),
    ]
