# Generated by Django 4.2.11 on 2024-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_gincana_imagen_alter_parada_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gincana',
            name='visibilidad',
            field=models.BooleanField(default=False, verbose_name='Visibilidad de la gincana: '),
        ),
    ]
