# Generated by Django 4.2.11 on 2024-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_gincana_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gincana',
            name='imagen_oscura',
            field=models.ImageField(blank=True, default='mapa_oscuro.png', null=True, upload_to='', verbose_name='Imagen oscura de la gincana'),
        ),
    ]
