# Generated by Django 4.2.11 on 2024-05-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_gincana_imagen_oscura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('usuario', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Invitado')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('gincana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.gincana')),
            ],
        ),
    ]
