# Generated by Django 4.2.11 on 2024-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_invitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='respondidas',
            field=models.IntegerField(default=0, verbose_name='Respondidas'),
        ),
    ]
